services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_corre_ai
      MYSQL_USER: aline
      MYSQL_PASSWORD: correai01
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: backend
    build: ./backend
    container_name: backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: db_corre_ai
      DB_USER: aline
      DB_PASS: correai01
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  db_data:
